'use client';
import { getStoredToken } from '@/lib/session';
import { useState } from 'react';
import { AlertTriangle, CheckCircle2, Globe2, LoaderCircle, ShieldCheck } from 'lucide-react';
import { clearExpiredAnalysisSession } from '@/lib/session';
import {useI18n} from '@/i18n';

const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000';
function getToken(){return getStoredToken()}
type URLResult={url:string;risk:string;risk_phrase:string;explanation:string;disclaimer:string;indicators:{code:string;label:string;evidence:string}[];observations:string[];what_was_checked:string[];what_could_not_be_checked:string[];verification_recommendations:string[];checks:Record<string,unknown>};
export default function URLPage(){const[url,setUrl]=useState('');const[result,setResult]=useState<URLResult|null>(null);const[error,setError]=useState('');const[busy,setBusy]=useState(false);const {language}=useI18n();
  async function run(){setBusy(true);setError('');setResult(null);try{const token=getToken();const response=await fetch(`${API}/api/analyze/url`,{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:JSON.stringify({text:url.trim(),channel:'url',language})});const data=await response.json();if(!response.ok)throw new Error(data.detail||'The URL could not be checked.');clearExpiredAnalysisSession(data);setResult(data)}catch(e){setError(e instanceof Error?e.message:'The URL could not be checked.')}finally{setBusy(false)}}
  return <div className="mx-auto max-w-[1080px] px-5 py-10 lg:px-8 lg:py-14"><div className="max-w-3xl"><div className="eyebrow">RAKSHAKAI · Link safety</div><h1 className="mt-2 text-3xl font-extrabold tracking-[-.035em] sm:text-4xl">Check a URL before opening it</h1><p className="mt-3 text-sm leading-6 text-[var(--muted)]">Review the URL format and domain for potential warning signs. The analyzer never opens, crawls, resolves, or follows the destination, including redirects.</p></div>
    <section className="surface-card mt-6"><label htmlFor="url" className="text-sm font-extrabold">URL to check</label><div className="mt-2 flex flex-col gap-3 sm:flex-row"><input id="url" className="input !my-0 flex-1" type="url" inputMode="url" maxLength={2000} value={url} onChange={e=>setUrl(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&url.trim())run()}} placeholder="https://example.com"/><button onClick={run} disabled={busy||!url.trim()} className="btn-primary min-w-[150px]">{busy?<><LoaderCircle className="animate-spin" size={16}/>Checking…</>:<><Globe2 size={16}/>Check URL</>}</button></div><p className="mt-3 text-[11px] leading-5 text-[var(--muted)]">Do not submit private links that contain account tokens or personal details. Query parameters and fragments are omitted from the returned URL preview.</p>{error&&<p role="alert" className="mt-3 rounded-lg bg-[#fff0ee] p-3 text-xs font-semibold text-[#a23e35]">{error}</p>}</section>
    {result&&<div className="mt-5 space-y-5"><section className="surface-card"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="eyebrow">URL analysis</div><h2 className="mt-2 break-all text-lg font-extrabold">{result.url}</h2></div><span className={`risk-pill risk-${result.risk}`}><AlertTriangle size={13}/>{result.risk_phrase}</span></div><p className="mt-4 text-sm leading-6 text-[var(--muted)]">{result.explanation}</p>{result.observations.length>0&&<div className="mt-4 space-y-2">{result.observations.map((x,i)=><p key={i} className="rounded-lg bg-[var(--bg)] p-3 text-xs leading-5">{x}</p>)}</div>}</section>
      <section className="grid gap-5 lg:grid-cols-2"><div className="surface-card"><h2 className="flex items-center gap-2 text-base font-extrabold"><AlertTriangle size={16} className="text-[#c77732]"/>Potential risk indicators</h2>{result.indicators.length?result.indicators.map(item=><div className="check-row" key={item.code}><span className="mt-0.5 text-[#c77732]">•</span><div><b className="text-xs">{item.label}</b><p className="mt-1 break-all text-[11px] text-[var(--muted)]">{item.evidence}</p></div></div>):<p className="mt-3 text-xs leading-5 text-[var(--muted)]">No configured URL pattern was detected. This does not establish that the site is safe.</p>}</div>
        <div className="surface-card"><h2 className="flex items-center gap-2 text-base font-extrabold"><CheckCircle2 size={16} className="text-[var(--accent)]"/>What was checked</h2><div className="mt-2">{result.what_was_checked.map(item=><p key={item} className="check-row text-xs">{item}</p>)}</div></div>
        <div className="surface-card"><h2 className="text-base font-extrabold">What could not be checked</h2><div className="mt-2">{result.what_could_not_be_checked.map(item=><p key={item} className="check-row text-xs">{item}</p>)}</div></div>
        <div className="surface-card"><h2 className="flex items-center gap-2 text-base font-extrabold"><ShieldCheck size={16} className="text-[var(--accent)]"/>Verification recommendations</h2><div className="mt-2">{result.verification_recommendations.map(item=><p key={item} className="check-row text-xs leading-5">{item}</p>)}</div></div>
      </section><p className="text-[11px] leading-5 text-[var(--muted)]">{result.disclaimer} “{result.risk_phrase}” describes observed patterns, not a fraud determination.</p></div>}
  </div>
}
