'use client';
import Link from 'next/link';
import { useI18n, type TranslationKey } from '@/i18n';
import { ArrowRight, CheckCircle2, FileSearch, Globe2, ImagePlus, LockKeyhole, MessageSquareText, Mic2, Play, ShieldAlert, Sparkles, UserRoundCheck } from 'lucide-react';

const features = [{icon:MessageSquareText,title:'home.featureMessage',text:'home.featureMessageText'},{icon:ImagePlus,title:'home.featureImage',text:'home.featureImageText'},{icon:Globe2,title:'home.featureLink',text:'home.featureLinkText'},{icon:FileSearch,title:'home.featurePlain',text:'home.featurePlainText'}];
export default function Landing(){const {t}=useI18n();return <>
  <section className="hero-grid overflow-hidden border-b border-[var(--line)]"><div className="mx-auto grid max-w-[1320px] items-center gap-14 px-5 py-16 sm:py-20 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:py-28">
    <div><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-[#b9ded5] bg-[var(--surface)] px-3 py-2 text-[11px] font-bold text-[var(--accent)]"><span className="h-2 w-2 rounded-full bg-[var(--accent)]"/> {t('home.badge')}</div><h1 className="max-w-2xl text-4xl font-extrabold leading-[1.05] tracking-[-.04em] sm:text-6xl">{t('home.title')}</h1><p className="mt-6 max-w-xl text-base leading-7 text-[var(--muted)] sm:text-lg">{t('home.description')}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link className="btn-primary" href="/login">{t('home.analyze')} <ArrowRight size={16}/></Link><Link className="btn-ghost" href="/login?next=%2Fanalyze%3Fmode%3Dimage"><ImagePlus size={16}/> {t('home.upload')}</Link></div><div className="mt-7 flex flex-wrap gap-x-5 gap-y-2 text-xs font-semibold text-[var(--muted)]"><span className="flex items-center gap-1.5"><CheckCircle2 size={14} className="text-[var(--accent)]"/> {t('home.noAdvice')}</span><span className="flex items-center gap-1.5"><CheckCircle2 size={14} className="text-[var(--accent)]"/> {t('home.privacy')}</span><span className="flex items-center gap-1.5"><CheckCircle2 size={14} className="text-[var(--accent)]"/> English · हिन्दी · ಕನ್ನಡ · मराठी · తెలుగు · മലയാളം</span></div></div>
    <div className="relative mx-auto w-full max-w-[490px]"><div className="absolute -right-6 -top-6 h-32 w-32 rounded-full bg-[#f7dcae] opacity-70 blur-2xl"/><div className="surface-card relative overflow-hidden !p-0"><div className="flex items-center justify-between border-b border-[var(--line)] px-5 py-4"><div className="flex items-center gap-2"><span className="brand-mark small"><ShieldAlert size={15}/></span><span className="text-xs font-bold">Safety scan</span></div><span className="text-[10px] font-bold text-[var(--muted)]">DEMO PREVIEW</span></div><div className="bg-[var(--bg)] px-5 py-5"><div className="rounded-xl border border-[var(--line)] bg-[var(--surface)] p-4"><div className="flex gap-3"><div className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-[#d9eaf7] text-xs font-bold text-[#467092]">A</div><div><p className="m-0 text-[11px] font-bold">Unknown contact · 10:42 AM</p><p className="mt-2 text-sm leading-6 text-[var(--ink)]">“Guaranteed 40% monthly returns. Act now to unlock your account.”</p></div></div></div><div className="mt-4 rounded-xl border border-[#f2d4bb] bg-[#fff8f0] p-4 dark:bg-[#382b21]"><div className="flex items-center justify-between"><span className="risk-pill risk-HIGH"><ShieldAlert size={12}/> HIGH RISK INDICATORS</span><span className="text-[10px] font-bold text-[#8d6b4d]">Pattern check only</span></div><p className="mt-3 text-xs leading-5 text-[#73563d] dark:text-[#e6bd8f]">Guaranteed returns and urgency were detected. These signals are not proof of fraud.</p><div className="mt-3 grid gap-2 text-[11px] font-semibold text-[#73563d] dark:text-[#e6bd8f]"><span>✓ Pause before sending money</span><span>✓ Verify through an official source</span></div></div></div></div><div className="absolute -bottom-5 -left-8 hidden items-center gap-3 rounded-xl border border-[var(--line)] bg-[var(--surface)] px-4 py-3 shadow-xl sm:flex"><span className="icon-tile !h-8 !w-8"><LockKeyhole size={15}/></span><span><span className="block text-[11px] font-bold">Private by design</span><span className="block text-[10px] text-[var(--muted)]">Your upload is not retained</span></span></div></div>
  </div></section>
  <section className="mx-auto max-w-[1320px] px-5 py-16 lg:px-8 lg:py-20"><div className="max-w-xl"><div className="eyebrow">{t('home.how')}</div><h2 className="mt-3 text-3xl font-extrabold tracking-[-.03em] sm:text-4xl">{t('home.clarity')}</h2><p className="mt-4 leading-7 text-[var(--muted)]">A calm, practical second look at content that asks for your trust, money or information.</p></div><div className="mt-10 grid gap-5 md:grid-cols-3"><div className="feature-card"><span className="icon-tile">01</span><h3 className="mt-5 text-lg font-bold">{t('home.step1')}</h3><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{t('home.step1Text')}</p></div><div className="feature-card"><span className="icon-tile">02</span><h3 className="mt-5 text-lg font-bold">{t('home.step2')}</h3><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{t('home.step2Text')}</p></div><div className="feature-card"><span className="icon-tile">03</span><h3 className="mt-5 text-lg font-bold">{t('home.step3')}</h3><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{t('home.step3Text')}</p></div></div></section>
  <section className="border-y border-[var(--line)] bg-[var(--surface)]"><div className="mx-auto max-w-[1320px] px-5 py-16 lg:px-8 lg:py-20"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><div className="eyebrow">{t('home.features')}</div><h2 className="mt-3 text-3xl font-extrabold tracking-[-.03em]">{t('home.featuresTitle')}</h2></div><Link className="text-sm font-bold text-[var(--accent)]" href="/education">{t('home.exploreSafety')} <ArrowRight className="ml-1 inline" size={15}/></Link></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{features.map(({icon:Icon,title,text})=><div className="feature-card !shadow-none" key={title}><span className="icon-tile"><Icon size={19}/></span><h3 className="mt-5 font-bold">{t(title as TranslationKey)}</h3><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{t(text as TranslationKey)}</p></div>)}</div></div></section>
  <section className="mx-auto grid max-w-[1320px] gap-10 px-5 py-16 lg:grid-cols-[.9fr_1.1fr] lg:items-center lg:px-8 lg:py-24"><div><div className="eyebrow">{t('home.privacyTitle')}</div><h2 className="mt-3 text-3xl font-extrabold tracking-[-.03em] sm:text-4xl">{t('home.privacyHeading')}</h2><p className="mt-5 leading-7 text-[var(--muted)]">{t('home.privacyBody')}</p><Link className="btn-secondary mt-7" href="/privacy">{t('home.privacyLink')} <ArrowRight size={16}/></Link></div><div className="grid gap-4 sm:grid-cols-2"><div className="surface-card"><LockKeyhole className="text-[var(--accent)]" size={22}/><h3 className="mt-5 font-bold">No hidden data grab</h3><p className="mt-2 text-sm leading-6 text-[var(--muted)]">We ask only for what helps you analyze content.</p></div><div className="surface-card"><UserRoundCheck className="text-[var(--accent)]" size={22}/><h3 className="mt-5 font-bold">Human judgment stays central</h3><p className="mt-2 text-sm leading-6 text-[var(--muted)]">An indicator is a prompt to verify, never a verdict.</p></div><div className="surface-card sm:col-span-2"><div className="flex items-center gap-3"><Mic2 className="text-[var(--accent)]" size={22}/><div><h3 className="font-bold">Made for India’s languages</h3><p className="mt-1 text-sm text-[var(--muted)]">Switch between English, हिन्दी and ಕನ್ನಡ. More languages can be added safely.</p></div></div></div></div></section>
  <section className="bg-[var(--navy)] text-white"><div className="mx-auto flex max-w-[1320px] flex-col items-start justify-between gap-7 px-5 py-14 sm:flex-row sm:items-center lg:px-8"><div><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.14em] text-[#7ce2ca]"><Sparkles size={14}/> Start with one message</div><h2 className="mt-3 max-w-lg text-3xl font-extrabold tracking-[-.03em]">{t('home.cta')}</h2></div><Link className="btn-primary !bg-[#7ce2ca] !text-[#123448]" href="/login">{t('home.open')} <ArrowRight size={16}/></Link></div></section>
  <div className="sr-only"><Play/></div>
</>}
