'use client';
import { getStoredToken } from '@/lib/session';
import { useEffect, useMemo, useState } from 'react';
import type { ReactNode } from 'react';
import { AlertTriangle, CheckCircle2, FileText, ImageUp, LoaderCircle, ShieldCheck, Upload } from 'lucide-react';
import { clearExpiredAnalysisSession } from '@/lib/session';
import {useI18n} from '@/i18n';

const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000';
type Indicator={code:string;label:string;evidence:string;start?:number;end?:number};
type Finding={code:string;title:string;reason:string;evidence:string;recommended_action:string};
type Result={filename?:string;extracted_text?:string;extraction_available?:boolean;extraction_method?:string;message?:string;risk:string;explanation:string;disclaimer?:string;indicators:Indicator[];findings?:Finding[];verification_steps?:string[];safe_next_actions?:string[]};
function getToken(){return getStoredToken()}

export default function DocumentAnalyzer({imagesOnly=false}:{imagesOnly?:boolean}){
  const {language}=useI18n();
  const [file,setFile]=useState<File|null>(null);const [objectUrl,setObjectUrl]=useState('');const [result,setResult]=useState<Result|null>(null);const [manual,setManual]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  useEffect(()=>{if(!file){setObjectUrl('');return}const url=URL.createObjectURL(file);setObjectUrl(url);return()=>URL.revokeObjectURL(url)},[file]);
  const accept=imagesOnly?'image/png,image/jpeg,image/webp':'.png,.jpg,.jpeg,.webp,.pdf,application/pdf,image/png,image/jpeg,image/webp';
  async function analyze(upload:boolean){setBusy(true);setError('');try{const token=getToken();let response:Response;if(upload){if(!file)throw new Error('Choose a file first.');const form=new FormData();form.append('file',file);response=await fetch(`${API}/api/${imagesOnly?'analyze/image':'analyze/document'}?language=${language}`,{method:'POST',headers:token?{Authorization:`Bearer ${token}`}:{ },body:form})}else{if(manual.trim().length<3)throw new Error('Paste at least three characters.');response=await fetch(`${API}/api/analyze/message`,{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:JSON.stringify({text:manual.trim(),channel:'document',language})})}const data=await response.json();if(!response.ok)throw new Error(data.detail||'The file could not be processed.');clearExpiredAnalysisSession(data);if(!upload){data.extracted_text=manual.trim();data.extraction_available=true;data.extraction_method='Manual paste'}setResult(data);if(data.extracted_text)setManual(data.extracted_text)}catch(e){setError(e instanceof Error?e.message:'The file could not be processed.')}finally{setBusy(false)}}
  return <div className="mx-auto max-w-[1180px] px-5 py-10 lg:px-8 lg:py-14"><div className="max-w-3xl"><div className="eyebrow">RAKSHAKAI · {imagesOnly?'Screenshot analyzer':'Screenshot & document analyzer'}</div><h1 className="mt-2 text-3xl font-extrabold tracking-[-.035em] sm:text-4xl">Review a file for safety signals</h1><p className="mt-3 text-sm leading-6 text-[var(--muted)]">Upload a screenshot or document to extract text and check for suspicious patterns. This analyzer does not connect to WhatsApp, Telegram, or any private account.</p></div>
    <div className="mt-6 grid gap-5 lg:grid-cols-[.85fr_1.15fr]"><section className="surface-card"><div className="eyebrow">1 · Choose a file</div><label className="dropzone mt-4 block cursor-pointer"><input type="file" className="sr-only" accept={accept} onChange={e=>{setFile(e.target.files?.[0]||null);setResult(null);setManual('');setError('')}}/><Upload size={26} className="mx-auto text-[var(--accent)]"/><span className="mt-3 block text-sm font-bold">{file?.name||'Select an image or PDF'}</span><span className="mt-1 block text-xs text-[var(--muted)]">{imagesOnly?'PNG, JPG, JPEG, or WEBP · 5 MB maximum':'PNG, JPG, JPEG, WEBP, or PDF · 10 MB maximum'}</span></label>
      {file&&objectUrl&&<div className="mt-4 overflow-hidden rounded-xl border border-[var(--line)] bg-[var(--bg)]"><div className="border-b border-[var(--line)] px-3 py-2 text-xs font-bold">Original file preview</div>{file.type==='application/pdf'||file.name.toLowerCase().endsWith('.pdf')?<iframe title="PDF preview" src={objectUrl} className="h-[420px] w-full"/>:<img src={objectUrl} alt="Uploaded screenshot preview" className="mx-auto max-h-[420px] max-w-full object-contain"/>}</div>}
      <p className="mt-4 text-xs leading-5 text-[var(--muted)]">Files are checked against their declared type and signature, processed in memory, and discarded after extraction. Executable files are not accepted. PDF limit: 20 pages.</p>
      <button onClick={()=>analyze(true)} disabled={!file||busy} className="btn-primary mt-4 w-full">{busy?<><LoaderCircle size={16} className="animate-spin"/>Processing…</>:<><ImageUp size={16}/>Upload and analyze</>}</button>
      {error&&<p role="alert" className="mt-3 rounded-lg bg-[#fff0ee] p-3 text-xs font-semibold text-[#a23e35]">{error}</p>}
    </section>
    <section className="space-y-5">{result&&<><div className="surface-card"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="eyebrow">2 · Extracted text</div><h2 className="mt-1 text-lg font-extrabold">{result.filename||'Pasted content'}{result.extraction_method&&<span className="ml-2 text-xs font-medium text-[var(--muted)]">· {result.extraction_method}</span>}</h2></div><span className={`risk-pill risk-${result.risk}`}>{result.risk} RISK</span></div>{result.extracted_text?<div className="mt-4 max-h-[320px] overflow-auto whitespace-pre-wrap rounded-xl bg-[var(--bg)] p-4 text-sm leading-6"><HighlightedText text={result.extracted_text} indicators={result.indicators||[]}/></div>:<p className="mt-3 text-sm leading-6 text-[var(--muted)]">{result.message||'No text was extracted.'}</p>}{!result.extraction_available&&<p className="mt-3 rounded-lg border border-[#f0d2af] bg-[#fff8ec] p-3 text-xs leading-5 text-[#8c5d2d]">Text extraction is unavailable. Paste the visible message text here to continue manually.</p>}</div>
      {result.explanation&&<div className="surface-card"><div className="eyebrow">3 · Safety analysis</div><h2 className="mt-1 text-lg font-extrabold">What we noticed</h2><p className="mt-3 text-sm leading-6 text-[var(--muted)]">{result.explanation}</p><div className="mt-3 space-y-2">{(result.findings||[]).map(f=><div key={f.code} className="check-row"><AlertTriangle size={15} className="mt-0.5 shrink-0 text-[#c77732]"/><div><b>{f.title}</b><p className="mt-1 text-xs leading-5 text-[var(--muted)]">{f.reason}</p><p className="mt-2 text-xs"><b>Safer action:</b> {f.recommended_action}</p></div></div>)}{!(result.findings||[]).length&&<p className="text-xs leading-5 text-[var(--muted)]">No configured patterns were found. A low result does not prove the content is safe.</p>}</div>{result.disclaimer&&<p className="mt-4 text-[10px] leading-5 text-[var(--muted)]">{result.disclaimer} This uses pattern based checks; it is not a legal finding or investment advice.</p>}</div>}
      {!!result.verification_steps?.length&&<div className="surface-card"><div className="eyebrow">4 · Recommendations</div><div className="mt-2">{result.verification_steps.map(step=><div className="check-row" key={step}><CheckCircle2 size={15} className="mt-0.5 shrink-0 text-[var(--accent)]"/><span className="text-xs leading-5">{step}</span></div>)}</div></div>}</>}
      <div className="surface-card"><label htmlFor="manual-text" className="text-sm font-extrabold">Paste text manually</label><p className="mt-1 text-xs text-[var(--muted)]">Use this fallback if OCR or PDF extraction is unavailable.</p><textarea id="manual-text" value={manual} onChange={e=>setManual(e.target.value)} rows={5} maxLength={12000} className="input mt-3 resize-y" placeholder="Paste the visible message text…"/><button onClick={()=>analyze(false)} disabled={busy||manual.trim().length<3} className="btn-ghost w-full">Analyze pasted text</button></div>
    </section></div><p className="mt-5 flex items-start gap-2 text-[11px] leading-5 text-[var(--muted)]"><ShieldCheck size={15} className="mt-0.5 shrink-0 text-[var(--accent)]"/>The default analyzer checks known text patterns. OCR may miss or misread content. Review the extracted text before relying on its result.</p>
  </div>
}

function HighlightedText({text,indicators}:{text:string;indicators:Indicator[]}){
  const marks=useMemo(()=>indicators.filter(i=>Number.isInteger(i.start)&&Number.isInteger(i.end)&&i.start!>=0&&i.end!>i.start!&&i.end!<=text.length).map(i=>({start:i.start!,end:i.end!,label:i.label})).sort((a,b)=>a.start-b.start),[text,indicators]);
  const parts:ReactNode[]=[];let cursor=0;for(const mark of marks){if(mark.start<cursor)continue;if(mark.start>cursor)parts.push(text.slice(cursor,mark.start));parts.push(<mark key={`${mark.start}-${mark.end}`} title={mark.label} className="rounded bg-[#ffe3aa] px-0.5 text-[#654815]">{text.slice(mark.start,mark.end)}</mark>);cursor=mark.end}if(cursor<text.length)parts.push(text.slice(cursor));return <>{parts}</>
}
