'use client';
import { clearStoredToken, getStoredToken } from '@/lib/session';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { usePathname, useRouter } from 'next/navigation';
import { Bell, ChevronDown, Menu, Moon, ShieldCheck, Sun, X, Siren, LogOut } from 'lucide-react';
import { ACTIVE_LANGUAGES, LANGUAGES, type Language, useI18n } from '@/i18n';

export function SiteShell({ children }: { children: React.ReactNode }) {
  const [open, setOpen] = useState(false); const [dark, setDark] = useState(false); const [signedIn, setSignedIn] = useState(false); const [sessionReady,setSessionReady]=useState(false); const pathname=usePathname(); const router=useRouter(); const {language,setLanguage,t}=useI18n();
  const publicPaths=['/','/login','/register','/forgot-password','/reset-password','/privacy','/terms','/safety'];
  const isPublic=publicPaths.includes(pathname)||pathname.startsWith('/platforms');
  useEffect(() => { setDark(localStorage.getItem('rakshakai_theme') === 'dark'); let active=true; const syncSession=async()=>{const token=getStoredToken();if(!token){if(active){setSignedIn(false);setSessionReady(true)}return}try{const response=await fetch(`${process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000'}/api/users/me`,{headers:{Authorization:`Bearer ${token}`}});if(!response.ok)throw new Error('Session expired');if(active){setSignedIn(true);setSessionReady(true)}}catch{clearStoredToken();if(active){setSignedIn(false);setSessionReady(true)}}};syncSession();window.addEventListener('rakshakai-session-change',syncSession);window.addEventListener('storage',syncSession);return()=>{active=false;window.removeEventListener('rakshakai-session-change',syncSession);window.removeEventListener('storage',syncSession)}; }, []);
  useEffect(()=>{if(!sessionReady)return;if(!signedIn&&!isPublic)router.replace('/login');else if(signedIn&&(pathname==='/login'||pathname==='/register'))router.replace('/dashboard')},[sessionReady,signedIn,isPublic,pathname,router]);
  useEffect(() => { document.documentElement.classList.toggle('dark', dark); localStorage.setItem('rakshakai_theme', dark ? 'dark' : 'light'); }, [dark]);
  return <div className="min-h-screen bg-[var(--bg)] text-[var(--ink)] transition-colors">
    <header className="sticky top-0 z-40 border-b border-[var(--line)] bg-[var(--surface)]/90 backdrop-blur-xl"><div className="mx-auto flex h-[72px] max-w-[1320px] items-center justify-between px-5 lg:px-8">
      <Link href="/" className="flex items-center gap-3" onClick={() => setOpen(false)}><span className="brand-mark"><ShieldCheck size={19} strokeWidth={2.4} /></span><span><span className="block text-[15px] font-extrabold tracking-[.12em]">RAKSHAK<span className="text-[var(--accent)]">AI</span></span><span className="hidden text-[9px] font-bold uppercase tracking-[.2em] text-[var(--muted)] sm:block">Investor safety shield</span></span></Link>
      <button className="icon-button lg:hidden" aria-label={open?'Close navigation menu':'Open navigation menu'} aria-expanded={open} aria-controls="primary-navigation" onClick={() => setOpen(!open)}>{open ? <X size={21}/> : <Menu size={21}/>}</button>
      <nav id="primary-navigation" className={`${open ? 'flex' : 'hidden'} absolute left-0 right-0 top-[72px] flex-col gap-1 border-b border-[var(--line)] bg-[var(--surface)] p-4 lg:static lg:flex lg:flex-row lg:items-center lg:border-0 lg:bg-transparent lg:p-0`}>
        {!signedIn&&<><Link className="nav-link" href="/" onClick={() => setOpen(false)}>{t('nav.home')}</Link><Link className="nav-link" href="/login" onClick={() => setOpen(false)}>{t('nav.signIn')}</Link><Link className="nav-login" href="/register" onClick={() => setOpen(false)}>Create account</Link></>}
        {signedIn&&<><Link className="nav-link" href="/dashboard" onClick={() => setOpen(false)}>Dashboard</Link><Link className="nav-link" href="/analyze" onClick={() => setOpen(false)}>{t('nav.analyze')}</Link><Link className="nav-link" href="/education" onClick={() => setOpen(false)}>{t('nav.education')}</Link><Link className="nav-link" href="/rights" onClick={() => setOpen(false)}>{t('nav.rights')}</Link><Link className="nav-link" href="/platforms" onClick={() => setOpen(false)}>Verify platforms</Link><Link className="nav-link emergency-nav" href="/emergency" onClick={() => setOpen(false)}><Siren size={15}/> Emergency Help</Link><span className="mx-1 hidden h-5 w-px bg-[var(--line)] lg:block" /></>}
        <label className="language-select"><span className="sr-only">{t('nav.language')}</span><select value={language} onChange={e=>setLanguage(e.target.value as Language)}>{ACTIVE_LANGUAGES.map(code=><option key={code} value={code}>{LANGUAGES[code].nativeName}</option>)}</select><ChevronDown size={13}/></label><button className="icon-button" aria-label={t('nav.theme')} onClick={() => setDark(!dark)}>{dark ? <Sun size={17}/> : <Moon size={17}/>}</button>
        {signedIn && <><Link className="icon-button" aria-label={t('nav.notifications')} href="/notifications"><Bell size={17}/></Link><Link className="profile-chip" href="/profile"><span className="avatar">RK</span><span className="hidden sm:block">{t('nav.account')}</span></Link><button className="icon-button" aria-label="Sign out" title="Sign out" onClick={()=>{clearStoredToken();router.replace('/login')}}><LogOut size={16}/></button></>}
      </nav></div></header>
    <main>{!sessionReady||(!signedIn&&!isPublic||signedIn&&(pathname==='/login'||pathname==='/register'))?<div className="shell"><p role="status">{sessionReady&&signedIn?'Opening your dashboard…':'Please sign in to continue…'}</p></div>:children}</main>
    <footer className="border-t border-[var(--line)] bg-[var(--surface)]"><div className="mx-auto grid max-w-[1320px] gap-10 px-5 py-12 sm:grid-cols-2 lg:grid-cols-[1.4fr_1fr_1fr_1fr] lg:px-8"><div><Link href="/" className="flex items-center gap-2"><span className="brand-mark small"><ShieldCheck size={15}/></span><span className="font-extrabold tracking-[.1em]">RAKSHAK<span className="text-[var(--accent)]">AI</span></span></Link><p className="mt-4 max-w-xs text-sm leading-6 text-[var(--muted)]">{t('footer.tagline')}</p></div><div><p className="footer-label">{t('footer.explore')}</p><div className="footer-links"><Link href="/analyze">{t('footer.analyze')}</Link><Link href="/education">{t('footer.education')}</Link><Link href="/rights">{t('footer.rights')}</Link></div></div><div><p className="footer-label">{t('footer.support')}</p><div className="footer-links"><Link href="/grievance">{t('footer.grievance')}</Link><Link href="/privacy">{t('footer.privacy')}</Link><Link href="/settings">{t('footer.settings')}</Link></div></div><div><p className="footer-label">{t('footer.promise')}</p><p className="text-sm leading-6 text-[var(--muted)]">{t('footer.promiseText')}</p></div></div><div className="mx-auto flex max-w-[1320px] flex-col gap-2 border-t border-[var(--line)] px-5 py-5 text-xs text-[var(--muted)] sm:flex-row sm:items-center sm:justify-between lg:px-8"><span>{t('footer.copyright')}</span><span>{t('footer.notice')}</span></div></footer>
    {signedIn&&<Link className="emergency-float" href="/emergency"><Siren size={17}/> <span>Emergency Help</span></Link>}
  </div>;
}
