'use client';
import { getStoredToken } from '@/lib/session';
import { useEffect, useState } from 'react';
import type { ReactNode } from 'react';
import { AlertTriangle, ArrowUpRight, CheckCircle2, Clock3, ImageUp, Link2, LockKeyhole, MessageCircle, Send, ShieldCheck, Users, Wallet } from 'lucide-react';
import { clearExpiredAnalysisSession } from '@/lib/session';
import {useI18n} from '@/i18n';

const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000';
type Platform='WhatsApp'|'Telegram';
type Finding={code:string;title:string;reason:string;evidence:string;recommended_action:string};
type Result={risk:string;explanation:string;disclaimer:string;extracted_text?:string;indicators:{code:string;label:string;evidence:string;start?:number;end?:number}[];findings:Finding[];verification_steps:string[];safe_next_actions:string[]};

function getToken(){return getStoredToken()}

export default function SocialSafetyAnalyzer({platform}:{platform:Platform}){
  const {language}=useI18n();
  const [mode,setMode]=useState<'paste'|'screenshot'>('paste');const [text,setText]=useState('');const [file,setFile]=useState<File|null>(null);const [fileUrl,setFileUrl]=useState('');const [result,setResult]=useState<Result|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [ocrNote,setOcrNote]=useState('');
  useEffect(()=>{if(!file){setFileUrl('');return}const url=URL.createObjectURL(file);setFileUrl(url);return()=>URL.revokeObjectURL(url)},[file]);
  const isWA=platform==='WhatsApp';
  async function analyze(){setBusy(true);setError('');setResult(null);setOcrNote('');try{
    const token=await getToken();let content=text.trim();
    if(mode==='screenshot'){
      if(!file)throw new Error('Choose a screenshot image first.');
      const form=new FormData();form.append('file',file);const imageResponse=await fetch(`${API}/api/analyze/image?language=${language}`,{method:'POST',headers:token?{Authorization:`Bearer ${token}`}:{ },body:form});const imageData=await imageResponse.json();
      if(!imageResponse.ok)throw new Error(imageData.detail||'Screenshot could not be processed.');
      content=(imageData.extracted_text||'').trim();
      if(!content){setOcrNote('The screenshot was received and discarded, but OCR is not configured on this server. Paste the message text below to continue analysis.');return;}
      clearExpiredAnalysisSession(imageData);setText(content);setResult(imageData);return;
    }
    if(content.length<3)throw new Error('Add at least three characters of message text.');
    const response=await fetch(`${API}/api/analyze/message`,{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:JSON.stringify({text:content,channel:isWA?'whatsapp':'telegram',language})});const data=await response.json();if(!response.ok)throw new Error(data.detail||'Analysis failed.');clearExpiredAnalysisSession(data);setResult(data);
  }catch(e){setError(e instanceof Error?e.message:'Analysis failed.')}finally{setBusy(false)}}
  const riskClass=result?.risk==='HIGH'?'risk-HIGH':result?.risk==='MODERATE'?'risk-MODERATE':result?.risk==='LOW'?'risk-LOW':'risk-UNKNOWN';
  return <div className="mx-auto max-w-[1180px] px-5 py-9 lg:px-8 lg:py-12">
    <div className="flex flex-wrap items-center gap-3"><span className="icon-tile !h-11 !w-11">{isWA?<MessageCircle size={20}/>:<SendIcon/>}</span><div><div className="eyebrow">RAKSHAKAI · {platform} safety</div><h1 className="mt-1 text-3xl font-extrabold tracking-[-.035em]">Check a message before you act</h1></div></div>
    <p className="mt-3 max-w-3xl text-sm leading-6 text-[var(--muted)]">Analyze text you choose to paste or a screenshot you upload. This is an independent safety analyzer, not the {platform} app. It never reads private chats, asks for platform credentials, or requests OTPs.</p>
    <div className="mt-6 rounded-xl border border-[#b9ded5] bg-[var(--accent-soft)] px-4 py-3 text-xs leading-5 text-[var(--accent)]"><b>Private by choice.</b> Submit only content you are comfortable analyzing. Submitted text is used for this check and is saved to your history only when you choose to sign in.</div>
    <div className="mt-6 grid items-start gap-5 lg:grid-cols-[1.08fr_.92fr]">
      <section className="surface-card !p-0 overflow-hidden">
        <div className="flex border-b border-[var(--line)] p-2"><button aria-pressed={mode==='paste'} onClick={()=>{setMode('paste');setError('');setOcrNote('');setResult(null)}} className={`flex-1 rounded-lg px-3 py-3 text-sm font-bold ${mode==='paste'?'bg-[var(--accent-soft)] text-[var(--accent)]':'text-[var(--muted)]'}`}>Paste a message</button><button aria-pressed={mode==='screenshot'} onClick={()=>{setMode('screenshot');setError('');setOcrNote('');setResult(null)}} className={`flex-1 rounded-lg px-3 py-3 text-sm font-bold ${mode==='screenshot'?'bg-[var(--accent-soft)] text-[var(--accent)]':'text-[var(--muted)]'}`}>Screenshot analyzer</button></div>
        <div className="p-5 sm:p-6">{mode==='paste'?<><label htmlFor="social-message" className="text-sm font-extrabold">Message content</label><textarea id="social-message" value={text} onChange={e=>{setText(e.target.value);setResult(null)}} maxLength={12000} rows={7} className="input mt-3 min-h-[170px] resize-y" placeholder="Paste copied message text here…"/><div className="-mt-3 mb-4 text-right text-[10px] text-[var(--muted)]">{text.length.toLocaleString()}/12,000</div></>:<><label className="dropzone block cursor-pointer"><input className="sr-only" type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{setFile(e.target.files?.[0]||null);setOcrNote('');setResult(null)}}/><ImageUp className="mx-auto text-[var(--accent)]" size={28}/><span className="mt-3 block text-sm font-bold">{file?file.name:'Choose a screenshot'}</span><span className="mt-1 block text-xs text-[var(--muted)]">PNG, JPG, or WEBP · up to 5 MB</span></label><p className="mt-3 text-xs leading-5 text-[var(--muted)]">Upload → OCR text extraction → message analysis. The image is discarded after processing. OCR must be configured by the server operator.</p></>}
          {error&&<p role="alert" className="mt-3 rounded-lg bg-[#fff0ee] p-3 text-xs font-semibold text-[#a23e35]">{error}</p>}{ocrNote&&<div role="status" className="mt-3 rounded-lg border border-[#f0d2af] bg-[#fff8ec] p-3 text-xs leading-5 text-[#8c5d2d]">{ocrNote}<button onClick={()=>setMode('paste')} className="ml-2 font-bold underline">Paste text</button></div>}
          <button onClick={analyze} disabled={busy||(mode==='paste'?text.trim().length<3:!file)} className="btn-primary mt-2 w-full">{busy?'Analyzing…':mode==='paste'?'Analyze message':'Upload and analyze screenshot'} <ArrowUpRight size={16}/></button>
          <div className="mt-4 flex items-center gap-2 text-[11px] text-[var(--muted)]"><LockKeyhole size={14}/> Never include passwords, OTPs, PINs, or recovery phrases.</div>
        </div>
      </section>
      <section className="surface-card">
        <div className="flex items-center justify-between"><div><div className="eyebrow">Preview</div><h2 className="mt-1 text-lg font-extrabold">{platform}-style message</h2></div><span className="rounded-full border border-[var(--line)] px-2.5 py-1 text-[10px] font-bold text-[var(--muted)]">Illustrative preview</span></div>
        {mode==='screenshot'&&file&&fileUrl&&<div className="mt-4 overflow-hidden rounded-xl border border-[var(--line)]"><div className="border-b border-[var(--line)] px-3 py-2 text-xs font-bold">Original screenshot</div><img src={fileUrl} alt="Selected messaging screenshot" className="mx-auto max-h-64 max-w-full object-contain"/></div>}
        <div className={`mt-4 rounded-2xl p-4 ${isWA?'bg-[#e9f4ed] dark:bg-[#1d332d]':'bg-[#eaf2fa] dark:bg-[#1c2d40]'}`}><div className="mx-auto mb-4 w-fit rounded-full bg-white/75 px-3 py-1 text-[10px] font-semibold text-slate-500">Today</div><div className="flex items-start gap-2"><div className={`grid h-8 w-8 shrink-0 place-items-center rounded-full text-xs font-bold text-white ${isWA?'bg-[#078b72]':'bg-[#398acb]'}`}>{isWA?'?':'S'}</div><div className="max-w-[90%] rounded-xl rounded-tl-sm bg-white p-3 text-[13px] leading-5 text-slate-800 shadow-sm"><span className="mb-1 block text-[10px] font-bold text-[#1385bd]">{text.trim()?`${platform} contact`:'Unknown contact'}</span>{text.trim()?text.trim().slice(0,900):'Your message preview will appear here after you paste content.'}{text.length>900?'…':''}<div className="mt-1 text-right text-[9px] text-slate-400">12:08 ✓✓</div></div></div><p className="mt-4 text-center text-[10px] font-semibold text-slate-500">Preview only · RAKSHAKAI is not {platform}</p></div>
        {!result&&<div className="mt-5 grid grid-cols-2 gap-2">{[['Promises','Guaranteed returns',Wallet],['Pressure','Urgent requests',Clock3],['Identity','Impersonation',ShieldCheck],['Links','Suspicious URLs',Link2]].map(([title,label,Icon]:any)=><div key={title} className="rounded-xl bg-[var(--bg)] p-3"><Icon size={16} className="text-[var(--accent)]"/><p className="mt-2 text-xs font-extrabold">{title}</p><p className="mt-1 text-[10px] text-[var(--muted)]">{label}</p></div>)}</div>}
      </section>
    </div>
    {result&&<section className="mt-5 grid gap-5 lg:grid-cols-[1.08fr_.92fr]"><div className="surface-card"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="eyebrow">Safety result · {result.indicators.length} indicator{result.indicators.length===1?'':'s'}</div><h2 className="mt-2 text-2xl font-extrabold">What we noticed</h2></div><span className={`risk-pill ${riskClass}`}><AlertTriangle size={13}/>{result.risk} RISK</span></div><p className="mt-4 text-sm leading-6 text-[var(--muted)]">{result.explanation}</p>{mode==='screenshot'&&result.extracted_text&&<div className="mt-4"><h3 className="text-sm font-extrabold">Extracted text · suspicious phrases highlighted</h3><div className="mt-2 max-h-56 overflow-auto whitespace-pre-wrap rounded-xl bg-[var(--bg)] p-4 text-xs leading-5">{highlightText(result.extracted_text,result.indicators)}</div></div>}<div className="mt-4 space-y-2">{result.findings.length?result.findings.map(f=><div className="rounded-xl border border-[var(--line)] p-4" key={f.code}><div className="flex items-start gap-2"><AlertTriangle size={15} className="mt-0.5 shrink-0 text-[#c77732]"/><div><h3 className="text-sm font-extrabold">{f.title}</h3><p className="mt-1 text-xs leading-5 text-[var(--muted)]">{f.reason}</p><p className="mt-2 break-words text-xs"><b>Evidence:</b> “{f.evidence}”</p></div></div></div>):<p className="rounded-xl bg-[var(--bg)] p-4 text-xs leading-5 text-[var(--muted)]">No configured patterns were detected. A low result does not establish that a message is safe.</p>}</div><p className="mt-4 text-[10px] leading-5 text-[var(--muted)]">{result.disclaimer} Pattern based analysis; not a legal finding or investment advice.</p></div><div className="surface-card"><div className="eyebrow">Keep yourself safe</div><h2 className="mt-2 text-xl font-extrabold">Verification steps</h2><div className="mt-3">{result.verification_steps.map((s,i)=><div className="check-row" key={s}><span className="grid h-5 w-5 shrink-0 place-items-center rounded-full bg-[var(--accent-soft)] text-[var(--accent)]"><CheckCircle2 size={13}/></span><span className="text-xs leading-5">{s}</span></div>)}</div><h3 className="mt-5 flex items-center gap-2 text-sm font-extrabold"><Users size={15}/> Safe actions</h3>{result.safe_next_actions.map(s=><p key={s} className="mt-2 rounded-lg bg-[var(--bg)] p-3 text-xs leading-5">{s}</p>)}</div></section>}
    <section className="mt-5 rounded-xl border border-[var(--line)] bg-[var(--surface)] px-4 py-3 text-xs leading-5 text-[var(--muted)]"><b className="text-[var(--ink)]">Optional {platform} integration:</b> disabled. Authorized business or bot integrations require operator configured API credentials and verified webhooks. This analyzer never connects to personal accounts or reads private conversations. {platform==='Telegram'&&<span>It does not provide trading recommendations.</span>}</section>
  </div>;
}
function SendIcon(){return <Send size={19}/>}
function highlightText(text:string,indicators:Result['indicators']){const ranges=indicators.filter(x=>Number.isInteger(x.start)&&Number.isInteger(x.end)&&x.start!>=0&&x.end!>x.start!&&x.end!<=text.length).map(x=>({start:x.start!,end:x.end!,label:x.label})).sort((a,b)=>a.start-b.start);const nodes:ReactNode[]=[];let i=0;for(const r of ranges){if(r.start<i)continue;if(r.start>i)nodes.push(text.slice(i,r.start));nodes.push(<mark key={`${r.start}-${r.end}`} title={r.label} className="rounded bg-[#ffe3aa] px-0.5 text-[#654815]">{text.slice(r.start,r.end)}</mark>);i=r.end}if(i<text.length)nodes.push(text.slice(i));return <>{nodes}</>}
