"""Editable seed content for the investor education center.

Examples are invented for training and do not describe real people, firms, or cases.
"""

LESSON_SEEDS = [
    ('fake-investment-schemes','Fake investment schemes','A scheme may use a convincing story or polished group to collect money without clear, verifiable activity. Marketing claims alone do not verify a business.','(Synthetic example) A chat group says members can pool money into a secret project, but provides no independently verifiable company details or written terms.',['No clear product or business activity','Returns depend on recruiting others','Pressure to transfer to a personal account'],['Identify the legal entity and independently check its registration in the relevant official public directory.','Ask for written terms, fees, and risks; verify contact details independently.']),
    ('guaranteed-returns','Guaranteed returns','Investment outcomes carry risk. Claims of fixed, unusually high, or risk-free returns deserve careful independent verification.','(Synthetic example) “Earn 30% every month with zero risk. Your money is guaranteed.”',['Fixed high gains described as certain','Risk described as zero','A deadline to invest immediately'],['Check the exact claim and named entity through current official public sources.','Read written terms and understand how the claimed return is generated.']),
    ('phishing','Phishing','A phishing message tries to move you to a deceptive page or persuade you to reveal information. A familiar logo or name does not prove who sent it.','(Synthetic example) “Your account needs verification today. Sign in at example.invalid to avoid suspension.”',['Unexpected sign-in or verification link','Lookalike spelling or shortened URL','Request for OTP, password, or PIN'],['Do not use the message link; enter the known website address yourself.','Contact the organization through details you find independently.']),
    ('impersonation','Impersonation','An impersonator borrows the name, logo, or authority of a real organization to gain trust or create fear.','(Synthetic example) A caller says they are from a regulator and must move your funds to a “protected account.”',['Unsolicited claim of official identity','Threats, secrecy, or urgent instructions','Request to transfer money or share a code'],['Find the organization’s official contact details yourself and ask whether the contact is genuine.','Do not transfer money to an account supplied by the caller.']),
    ('fake-advisors','Fake advisors','Someone may falsely claim professional status, registration, or special access. A title in a profile is not proof of authorization.','(Synthetic example) “I am a certified market advisor. Pay my private account and I will send guaranteed calls.”',['Credentials cannot be independently confirmed','Private payment account','Guaranteed calls or pressure to act'],['Verify the person and firm through the applicable official public register.','Check the written service terms and fee recipient independently.']),
    ('fake-trading-platforms','Fake trading platforms','A fabricated or lookalike platform may display invented balances or block withdrawals while requesting more payments.','(Synthetic example) A new app shows a large profit, then asks for a “release tax” before funds can be withdrawn.',['Unsolicited app download link','Balance cannot be independently confirmed','Repeated withdrawal or release fees'],['Find the platform through an independent official source, not the message link.','Contact your bank or payment provider using its official channel if money was sent.']),
    ('social-media-scams','Social-media scams','Social posts and direct messages can use copied testimonials, fake giveaways, or coordinated pressure to attract payments.','(Synthetic example) A public post claims a celebrity doubled followers’ money and asks users to message a wallet address.',['Testimonials that cannot be verified','Impersonated accounts or copied posts','Payment required to claim a prize or profit'],['Check the account and announcement through the person or organization’s verified official channels.','Do not pay to unlock a prize or supposed return.']),
    ('whatsapp-scams','WhatsApp scams','WhatsApp messages can impersonate contacts, businesses, or groups. A familiar display name does not authenticate the sender.','(Synthetic example) “This is my new number. Send the deposit now; I cannot take a call.”',['Unexpected number or changed payment details','Urgency and refusal to verify by voice','Requests for OTPs or payments'],['Contact the person using a number already saved or another trusted channel.','Confirm payment details with the intended recipient before sending.']),
    ('telegram-scams','Telegram scams','Telegram groups and bots may circulate fake signals, impersonate admins, or use referral rewards to attract deposits.','(Synthetic example) A group admin promises guaranteed returns, asks for a seed phrase, and offers a bonus for inviting friends.',['Guaranteed gains or fake authority claims','Requests for recovery phrases or private keys','Deposit and referral pressure'],['Verify any named organization outside the group using an official source.','Never share recovery phrases, private keys, passwords, or one-time codes.']),
    ('referral-scams','Referral scams','A referral offer becomes concerning when rewards rely on recruiting people, required payments, or unclear underlying activity.','(Synthetic example) “Pay a joining fee and invite five friends to unlock the next guaranteed payout.”',['Income tied mainly to recruitment','Joining fee or escalating tiers','No clear product, written terms, or risk disclosure'],['Ask what real product or service is sold and read all written terms.','Do not pay or recruit others while essential details remain unclear.']),
]

NEVER_SHARE=['Passwords, PINs, or one-time passcodes (OTPs).','Banking credentials, card security codes, or remote-access permissions.','Wallet seed phrases, recovery phrases, or private keys.']

def build_lesson(seed):
    slug,title,explanation,example,signs,verify=seed
    quiz=[
        {'question':'Which signal deserves a closer check in this example?','options':[signs[0],'A contact method found independently','Taking time to read written terms'],'correct_index':0,'explanation':'The example is synthetic. The warning sign is a reason to pause and verify, not proof by itself.'},
        {'question':'What is a safer next step?','options':[verify[0],'Use the link or number supplied in the message','Send money first and check later'],'correct_index':0,'explanation':'Use information you find independently and take time to verify.'},
        {'question':'How should you treat the example?','options':['As an invented training example, not a real case','As a verified report about a real person','As an offer or recommendation'],'correct_index':0,'explanation':'Every example in this learning center is synthetic and is not investment advice.'},
    ]
    return {'slug':slug,'title':title,'simple_explanation':explanation,'synthetic_example':example,'warning_signs':signs,'what_to_verify':verify,'never_share':NEVER_SHARE,'if_suspicious':['Pause. Do not click, pay, recruit, or share information while checking.','Save relevant messages or receipts securely if you may need them.','Contact the named organization through independently found official details.','If you already sent money or credentials, contact your bank or relevant service through its official channel promptly.'],'quiz':quiz}

LESSONS=[build_lesson(seed) for seed in LESSON_SEEDS]
