"""Maintained public guidance content. Update these records after editorial review."""

RIGHTS_GUIDES=[
 {'slug':'investor-rights','title':'Investor rights','category':'rights','content':{'summary':'Understand the terms of a financial service and know how to contact the organization through verified channels. This guide is general education, not legal advice.','steps':['Read current written terms before agreeing.','Ask the provider how to raise a concern and where to find its published process.','Keep a copy of relevant terms and communications.']}},
 {'slug':'understanding-disclosures','title':'Understanding disclosures','category':'rights','content':{'summary':'Disclosures describe conditions, fees, and risks that can affect a financial product or service.','steps':['Read the complete current document, including fees, risks, and withdrawal conditions.','Ask the organization for clarification in writing.','Verify the document and named organization through official sources you find independently.']}},
 {'slug':'keeping-records','title':'Keeping transaction records','category':'rights','content':{'summary':'Organized records can help you explain what happened when seeking support. Keep them stored securely.','steps':['Record relevant dates, amounts, reference numbers, and contact methods.','Keep original messages, receipts, and account statements when safe to do so.','Do not post personal or financial records publicly.']}},
 {'slug':'official-communication','title':'Recognizing official communication','category':'rights','content':{'summary':'A logo, caller ID, badge, or display name does not by itself authenticate a message.','steps':['Find the organization’s website or phone number independently.','Compare the exact domain and contact details with that independent source.','Ask the organization to confirm the communication through its published channel.']}},
 {'slug':'safe-communication','title':'Safe communication','category':'rights','content':{'summary':'Use contact channels you verify independently and protect account access information.','steps':['Do not share passwords, PINs, OTPs, recovery phrases, or remote access.','Do not act on payment changes received only in an unexpected message.','Pause and confirm sensitive requests using a known, separate contact channel.']}},
 {'slug':'general-grievance-process','title':'General grievance process','category':'rights','content':{'summary':'The correct route depends on the organization and issue. This general guide does not name a regulator-specific route or submit a complaint.','steps':['Write a factual timeline and identify the organization and service involved.','Collect relevant records and keep copies in a secure place.','Find the organization’s current grievance process on its official website.','Follow the instructions published there and keep any acknowledgement or reference number.','If money or account access may be at risk, contact your bank or service provider through its independently verified channel promptly.']}},
]

GRIEVANCE_GUIDES=[
 {'slug':'suspicious-communication','title':'Suspicious communication','category':'suspicious_communication','content':{'relevant_information':['Date and time, sender details, message or call records, and links as plain text.','Whether any money, code, document, or account detail was shared.'],'guidance':['Do not reply, click links, pay, or share more information while checking.','Verify the claimed organization through contact details you find independently.'],'official_channel_guidance':'Use the organization’s own published contact and grievance details. Verify the domain independently; this guide does not provide a filing link.'}},
 {'slug':'unauthorized-transaction','title':'Unauthorized transaction','category':'unauthorized_transaction','content':{'relevant_information':['Transaction date, amount, payment reference, and account or payment provider involved.','A factual timeline and relevant statements or receipts. Do not share full account numbers here.'],'guidance':['Contact your bank or payment provider promptly using its official app, card, or website contact details.','Ask how to secure the account and record the support reference.'],'official_channel_guidance':'Use the current contact and dispute process published by your own bank or payment provider. This guide does not file a report.'}},
 {'slug':'impersonation','title':'Impersonation','category':'impersonation','content':{'relevant_information':['The name and organization claimed, sender handle or number, and date.','What the sender requested and whether any response or payment was made.'],'guidance':['Pause contact and do not send money or credentials.','Ask the named organization to verify the contact using details found independently.'],'official_channel_guidance':'Contact the organization through its official website or published number. No organization-specific link is asserted here.'}},
 {'slug':'service-complaint','title':'Service complaint','category':'service_complaint','content':{'relevant_information':['The service or product, issue, dates, prior reference numbers, and steps already taken.','Copies of relevant correspondence and terms, with sensitive credentials removed.'],'guidance':['Describe the issue factually and state the resolution you are seeking.','Submit through the provider’s published grievance process and keep its acknowledgement.'],'official_channel_guidance':'Use the current grievance process published by the relevant organization. The correct route varies by provider and issue.'}},
 {'slug':'account-access','title':'Account or credential concern','category':'account_access','content':{'relevant_information':['Which account or service may be affected and when the request or exposure occurred.','Whether an OTP, password, recovery phrase, or remote-access session was shared. Never include the secret itself.'],'guidance':['Use the official app or website that you open yourself to secure the account.','Contact the account provider through its independently verified channel.'],'official_channel_guidance':'Use the affected provider’s official security or support channel. This guide does not submit a complaint or change account settings.'}},
]
